name: universite_qr_code
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.4.0
  shared_preferences: ^2.0.18
  firebase_core: ^2.7.0
  flutter_lints: ^2.0.0
  cloud_firestore: ^4.4.4
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  flutter_barcode_scanner: ^2.0.0
  assets_audio_player: ^3.0.6
  flutter_plugin_tools: ^0.13.4+3
  flutter_native_splash: ^2.2.19
  introduction_screen: ^3.1.7
  floating_action_bubble: ^1.1.4
  shimmer: ^3.0.0

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/Services universitaires.png"



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pngwing.com (11).png"

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/sound/

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 300
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 700
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo-Regular.ttf
            weight: 300
          - asset: assets/fonts/Cairo-Medium.ttf
            weight: 500
          - asset: assets/fonts/Cairo-SemiBold.ttf
            weight: 900
      - family: EduSABeginner
        fonts:
          - asset: assets/fonts/EduSABeginner-VariableFont_wght.ttf
            weight: 300
      - family: JosefinSans
        fonts:
          - asset: assets/fonts/JosefinSans-Regular.ttf
            weight: 300
          - asset: assets/fonts/JosefinSans-Medium.ttf
            weight: 500
          - asset: assets/fonts/JosefinSans-SemiBold.ttf
            weight: 900
      - family: RobotoSlab
        fonts:
          - asset: assets/fonts/RobotoSlab-Regular.ttf
            weight: 300
          - asset: assets/fonts/RobotoSlab-Medium.ttf
            weight: 500
          - asset: assets/fonts/RobotoSlab-SemiBold.ttf
            weight: 900
